### ISSUE TITLE
Tile flickering

### ISSUE THREAD

**Issue by benjamin21st** [jackyrusly/jrgame#2]
Hey, thanks for making this available, such a great project and example for learning Phaser. But I noticed something that I didn't see in your demo, when I move character around, the tile seems to be flickering, it happens when both moving horizontally or vertically:
![screen shot 2018-10-21 at 11 37 38 am](https://user-images.githubusercontent.com/8607086/47269001-e490c800-d525-11e8-9908-fa1c7e05272e.jpg)

**Comment by JohnSlaughter** [comment]
This is a side-effect of WebGL.  You can eliminate it by using tile extrusion to make the neighboring tile colors not bleed through.

You can find it here:  https://github.com/sporadic-labs/tile-extruder

**Comment by benjamin21st** [comment]
@JohnSlaughter Ah I see, thanks for letting me know. I'll close this then!

**Comment by JohnSlaughter** [comment]
You can replace these two files in the **client/assets/maps** folder to fix it.
- town.png
- town.json

Here are the modified files, and a running example with the issue resolved:

- http://john7.com/misc/jrgame/
- http://node.john7.com:4000

If you change the name if the .png file, you'll also need to change it in the JSON file and  **/client/scenes/Init.js**.

**Comment by benjamin21st** [comment]
@JohnSlaughter Awesome, thanks John!
